import type { ShipConfig, ShipId } from '../types';

export const SHIP_CONFIGS: Record<ShipId, ShipConfig> = {
  vanguard: {
    id: 'vanguard',
    nameKey: 'ship_vanguard_name',
    titleKey: 'ship_vanguard_title',
    descKey: 'ship_vanguard_desc',
    specialPerkKey: 'ship_vanguard_perk',
    specialPerkDescKey: 'ship_vanguard_perk_desc',
    startingWeapon: 'plasma_blaster',
    cost: 0,
    unlockedByDefault: true,
    statModifiers: {
      maxHpMult: 1.0,
      armorBonus: 0,
      speedMult: 1.0,
      critChanceBonus: 0,
      attackSpeedMult: 1.0,
      pickupRadiusMult: 1.15,
    },
    color: '#00e5ff',
    glowColor: 'rgba(0, 229, 255, 0.8)',
    hullAccent: '#3b82f6',
  },
  interceptor: {
    id: 'interceptor',
    nameKey: 'ship_interceptor_name',
    titleKey: 'ship_interceptor_title',
    descKey: 'ship_interceptor_desc',
    specialPerkKey: 'ship_interceptor_perk',
    specialPerkDescKey: 'ship_interceptor_perk_desc',
    startingWeapon: 'piercing_laser',
    cost: 250,
    unlockedByDefault: false,
    statModifiers: {
      maxHpMult: 0.80,
      armorBonus: 0,
      speedMult: 1.25,
      critChanceBonus: 0.18,
      attackSpeedMult: 1.12,
      pickupRadiusMult: 1.0,
    },
    color: '#ec4899',
    glowColor: 'rgba(236, 72, 153, 0.8)',
    hullAccent: '#f43f5e',
  },
  dreadnought: {
    id: 'dreadnought',
    nameKey: 'ship_dreadnought_name',
    titleKey: 'ship_dreadnought_title',
    descKey: 'ship_dreadnought_desc',
    specialPerkKey: 'ship_dreadnought_perk',
    specialPerkDescKey: 'ship_dreadnought_perk_desc',
    startingWeapon: 'scatter_cannon',
    cost: 500,
    unlockedByDefault: false,
    statModifiers: {
      maxHpMult: 1.60,
      armorBonus: 4,
      speedMult: 0.85,
      critChanceBonus: -0.02,
      attackSpeedMult: 0.95,
      pickupRadiusMult: 1.20,
    },
    color: '#f59e0b',
    glowColor: 'rgba(245, 158, 11, 0.8)',
    hullAccent: '#d97706',
  },
  technomancer: {
    id: 'technomancer',
    nameKey: 'ship_technomancer_name',
    titleKey: 'ship_technomancer_title',
    descKey: 'ship_technomancer_desc',
    specialPerkKey: 'ship_technomancer_perk',
    specialPerkDescKey: 'ship_technomancer_perk_desc',
    startingWeapon: 'lightning_coil',
    cost: 750,
    unlockedByDefault: false,
    statModifiers: {
      maxHpMult: 0.90,
      armorBonus: 0,
      speedMult: 1.05,
      critChanceBonus: 0.05,
      attackSpeedMult: 1.25,
      pickupRadiusMult: 1.40,
    },
    color: '#10b981',
    glowColor: 'rgba(16, 185, 129, 0.8)',
    hullAccent: '#059669',
  },
  pyroclast: {
    id: 'pyroclast',
    nameKey: 'ship_pyroclast_name',
    titleKey: 'ship_pyroclast_title',
    descKey: 'ship_pyroclast_desc',
    specialPerkKey: 'ship_pyroclast_perk',
    specialPerkDescKey: 'ship_pyroclast_perk_desc',
    startingWeapon: 'toxic_aura',
    cost: 1000,
    unlockedByDefault: false,
    statModifiers: {
      maxHpMult: 1.20,
      armorBonus: 2,
      speedMult: 0.95,
      critChanceBonus: 0.05,
      attackSpeedMult: 1.0,
      pickupRadiusMult: 1.10,
    },
    color: '#f97316',
    glowColor: 'rgba(249, 115, 22, 0.85)',
    hullAccent: '#c2410c',
  },
  valkyrie: {
    id: 'valkyrie',
    nameKey: 'ship_valkyrie_name',
    titleKey: 'ship_valkyrie_title',
    descKey: 'ship_valkyrie_desc',
    specialPerkKey: 'ship_valkyrie_perk',
    specialPerkDescKey: 'ship_valkyrie_perk_desc',
    startingWeapon: 'seeker_missiles',
    cost: 1250,
    unlockedByDefault: false,
    statModifiers: {
      maxHpMult: 1.05,
      armorBonus: 1,
      speedMult: 1.10,
      critChanceBonus: 0.08,
      attackSpeedMult: 1.05,
      pickupRadiusMult: 1.15,
    },
    color: '#8b5cf6',
    glowColor: 'rgba(139, 92, 246, 0.85)',
    hullAccent: '#7c3aed',
  },
  chronos: {
    id: 'chronos',
    nameKey: 'ship_chronos_name',
    titleKey: 'ship_chronos_title',
    descKey: 'ship_chronos_desc',
    specialPerkKey: 'ship_chronos_perk',
    specialPerkDescKey: 'ship_chronos_perk_desc',
    startingWeapon: 'orbiting_blades',
    cost: 1500,
    unlockedByDefault: false,
    statModifiers: {
      maxHpMult: 0.95,
      armorBonus: 1,
      speedMult: 1.15,
      critChanceBonus: 0.10,
      attackSpeedMult: 1.15,
      pickupRadiusMult: 1.20,
    },
    color: '#06b6d4',
    glowColor: 'rgba(6, 182, 212, 0.85)',
    hullAccent: '#0891b2',
  },
  phantom: {
    id: 'phantom',
    nameKey: 'ship_phantom_name',
    titleKey: 'ship_phantom_title',
    descKey: 'ship_phantom_desc',
    specialPerkKey: 'ship_phantom_perk',
    specialPerkDescKey: 'ship_phantom_perk_desc',
    startingWeapon: 'piercing_laser',
    cost: 2000,
    unlockedByDefault: false,
    statModifiers: {
      maxHpMult: 0.85,
      armorBonus: 0,
      speedMult: 1.30,
      critChanceBonus: 0.20,
      attackSpeedMult: 1.20,
      pickupRadiusMult: 1.25,
    },
    color: '#e2e8f0',
    glowColor: 'rgba(226, 232, 240, 0.9)',
    hullAccent: '#64748b',
  },
};
